### PR TITLE
add Josef Holzmayr

### PR DESCRIPTION
**Pull request by TheYoctoJester**
Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>

### CODE REVIEW

**Review by fharper — CHANGES_REQUESTED** [review]
Can you fix the LinkedIn URL please?

I may just change that for putting the vanity URL for LinkedIn and Twitter handle only in the future, and didn't implemented a JSON validation process yet 😅

**Comment by TheYoctoJester** [comment]
@fharper it is probably not active yet as I just got rid of the "-xyz1234" suffix a moment ago. Can you just keep the PR open, I'll check it again tomorrow and then fix accordingly if needed?

**Comment by fharper** [comment]
Oh no sorry, just need to add ` https://` in front caused depending on what you use to render the Markdown, it may not be taken as a valid link, even if it is.

**Review by fharper — APPROVED** [review]
LGTM

**Pull request merged**
