### PR TITLE
Add Vishruth

### PR DESCRIPTION
**Pull request by theharithsa**
- Added new member from Observability Industry

### CODE REVIEW

**Review by fharper — CHANGES_REQUESTED** [review]
The Calendly link is 404

**Comment by theharithsa** [comment]
Link was broken so I fixed it now. The same link in the file is working now.

**Review by fharper — APPROVED** [review]
Thanks for offering free coffee chat @theharithsa 🫶

**Comment by theharithsa** [comment]
In the coffeechat now. Yay!!

**Pull request merged**
