### PR TITLE
Add Mike Lyons to people.json

### PR DESCRIPTION
**Pull request by mikelyons**

### CODE REVIEW

**Review by fharper — APPROVED** [review]
Thanks for offering free coffee chat @mikelyons 🫶

**Comment by fharper** [comment]
Oh @mikelyons I missed the fact that your commit isn't signed, can you sign it please? See https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Review by fharper — CHANGES_REQUESTED** [review]
Sorry for the spam, I already mentioned the signing issue, but forgot to request changes so it doesn't show as approved :)

**Comment by mikelyons** [comment]
I wont be able to sign the commit in the near-term.
What is the purpose of signing the commit? Thanks

**Comment by fharper** [comment]
> I wont be able to sign the commit in the near-term

No worries! You can do it when you have a couple of minutes free, it's quite straigthforward and will be useful if you contribute to other repositories :)

> What is the purpose of signing the commit?

It's a best practice for any repositories, mainly to ensure there is no impersonification. There are some horror stories with popular libraries out there. As for this repository, it's way less critical of course, but it ensures nobody is adding someone's else personal information, and since it's standard procedure, usually not an issue.

**Comment by mikelyons** [comment]
I was able to sign the most recent commit, but it appears that the check is still failing? please advise

**Comment by fharper** [comment]
@mikelyons: yeah, the first commit isn't sign. You can amend a previous commit to sign it, or if it's easier for you, you can close this PR and create a new one with just one commit.

**Pull request closed without merging**
